### ISSUE TITLE
Convert bike segments to ebike: Uncaught TypeError: Cannot read property 'document' of null

### ISSUE THREAD

**Issue by happybear88** [nickbeeton/garminstuff#2]
Hi Nick!

I'm trying to copy the segments with your script and it's not working for me on latest Chrome or Edge Dev.

1. Install tampermonkey and the script
2. Open e-bike ride → click either "Copy..." button.
Actual Result: editing ride opens in a new tab → ride type changes to bike ride → ride opens → "Changing activity type..." displays, then disappears. No further activity.

The ride is displayed as e-bike ride, but if I reload the page, it's actually a bike ride.
Error in Dev tools is logged.

```
userscript.html?id=4466143e-71ac-49e4-928a-37365c5c5afc:57 Uncaught TypeError: Cannot read property 'document' of null
    at window.h (userscript.html?id=4466143e-71ac-49e4-928a-37365c5c5afc:57)
window.h @ userscript.html?id=4466143e-71ac-49e4-928a-37365c5c5afc:57
setTimeout (async)
window.g @ userscript.html?id=4466143e-71ac-49e4-928a-37365c5c5afc:55
setTimeout (async)
window.f @ userscript.html?id=4466143e-71ac-49e4-928a-37365c5c5afc:53
window.f2 @ userscript.html?id=4466143e-71ac-49e4-928a-37365c5c5afc:165
```
GIF removed

Do you have any thoughts?

Thanks,
Vadim

**Comment by nickbeeton** [comment]
Hi Vadim,

Thanks for letting me know and for the helpful description! I can't think what would be causing it off the top of my head, but if you could do these two things for me it might help:

1) It looks like you don't have the latest version by the line numbers? If you click on the tamperscript logo there should be an option "Check for userscript updates". It probably won't fix it but worth a try!

2) If you could save the web page of your ebike ride (just the html is fine) and send it to me I might be able to see if there's anything different - I'm wondering if maybe some of the source is in Russian and my script isn't working because it's looking for English key words. If you're worried about privacy at all, feel free to strip anything out of the html you don't want me to see.

Cheers,
Nick

**Comment by happybear88** [comment]
Hi Nick,

Thanks for getting back with me.

1. That's the latest version of the script, I just installed it today. No updates found anyway.

2. The only Cyrillic is in the ride title, the rest is the standard English UI. Here's the [complete web-page](removed).

Cheers!
Vadim

**Comment by nickbeeton** [comment]
Hmm, still trying to think - have you disabled pop-up blockers and things like that? (though the script already opened one window so that's probably not it). Also is your connection slow? If it takes a while to load a page it might be too long for the timeouts I've got in the script.

Failing that, if you could go to your ride and click "create a new segment" and send me that html too, I can keep investigating there. It's hard to diagnose what's wrong when the same script is working fine on Chrome for me... but I'll keep thinking!

**Comment by happybear88** [comment]
Pop-up blockers have been disabled, and pop-ups for Strava have been explicitly allowed. 
The connection speed is all right in general.

Before I send another HTML, I'd like to play with the timeouts. Judging by the gif, which code lines should I look at?

**Comment by happybear88** [comment]
Ok, I just increased all timeouts I found by 3-5 seconds, and it worked! Thanks for your help, Nick!

**Comment by nickbeeton** [comment]
Glad we worked it out! Let me know if you have any more problems. I'm a scientist so I'm not used to writing code for public consumption so it's pretty ad-hoc :D
